### ISSUE TITLE
Yarn 2 install fails

### ISSUE THREAD

**Issue by milonite** [MetaMask/metamask-plugin-beta#155]
While installing the packages with yarn install I get the following error:

Script name: install
SyntaxError: Expected "$", "$(", "${", "'", "\"", "\\", or [ \t] but "&" found (line 1, column 36).
    at Xe (/home/user123/Documents/metamask-snaps/.yarn/releases/yarn-berry.js:36:319546)
    at Object.parse (/home/user123/Documents/metamask-snaps/.yarn/releases/yarn-berry.js:36:328965)
    at Object.t.parseShell (/home/user123/Documents/metamask-snaps/.yarn/releases/yarn-berry.js:36:314750)
    at Object.t.execute (/home/user123/Documents/metamask-snaps/.yarn/releases/yarn-berry.js:24:16728)
    at B.A.configuration.reduceHook (/home/user123/Documents/metamask-snaps/.yarn/releases/yarn-berry.js:24:5025)
    at Object.B [as executePackageScript] (/home/user123/Documents/metamask-snaps/.yarn/releases/yarn-berry.js:24:5158)
~

Seems an issue with Yarn 2?

Yarn version: 2.0.0-rc.29
Ubuntu 18.04.4 LTS

**Comment by Gudahtt** [comment]
I'm not sure why that doesn't work - I've never tried building with Yarn 2. We don't currently support using Yarn 2 to build the project though - we use Yarn v1, version 1.16 or greater ([see here](https://github.com/MetaMask/metamask-snaps-beta/blob/develop/package.json#L310))

**Comment by milonite** [comment]
yes, I switched to yarn 1.22.0 and works fine. Maybe this can be added to the documentation or enforced in the package.json engines with yarn<2.0.0

**Comment by Gudahtt** [comment]
Enforcement of the `engines` field is (as far as I know) at the discretion of the package manager you're using, which is a bit of a problem in this case since it's crashing 😅.

I don't have time to look into this now, but ideally I'd like to see if we can fix this first before we decide to document it as a problem. Unless it's a difficult one to solve anyway.

This problem aside, I think another alternative would be to commit a `.yarn` file that tells Yarn that we prefer to use v1. We'd need to increase the minimum supported Yarn version to one that supports that policy, but that's fine.

We'll get around to one or both of these things eventually, but feel free to give it a shot yourself if you're up to it! We would accept a PR that improves this situation (though that PR should be directed at the [main `metamask-extension` repo](https://github.com/MetaMask/metamask-extension), which this is a fork of).
