### ISSUE TITLE
Cannot find module: @babel/runtime

### ISSUE THREAD

**Issue by jvluso** [MetaMask/metamask-plugin-beta#64]
I'm trying to get started and am getting an error when I try to build the current version. 
```
[19:07:59] 'build:extension:js:deps:ui' errored after 8.08 s
[19:07:59] Error: Cannot find module '@babel/runtime/core-js/map' from '/home/jeremy/metamask-plugin-beta/node_modules/@material-ui/core/styles'
    at /home/jeremy/metamask-plugin-beta/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/jeremy/metamask-plugin-beta/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/jeremy/metamask-plugin-beta/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/jeremy/metamask-plugin-beta/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/jeremy/metamask-plugin-beta/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/jeremy/metamask-plugin-beta/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:153:21)
```
I've tried installing babel/runtime, and reinstalling gulp

**Comment by danfinlay** [comment]
Sorry for the slow reply, took a week off right after Devcon. We're back now!

Did you `npm install`, or did you follow [the readme](https://github.com/MetaMask/metamask-plugin-beta/blob/develop/README.md), which recommends using node v10 and `yarn` to install the dependencies?

**Comment by rekmarks** [comment]
To add to Dan's question, what script from `package.json` are you running when you encounter this error?

Edit: Ideally, it should be `yarn start`.

**Comment by jvluso** [comment]
Updating node and using `yarn` and `yarn dist` instead of `npm i` and `npm run dist` solved the problem. Thank you.

**Comment by milonite** [comment]
Would it make sense to prevent people to use npm in this case? 
Something like
 "engines": {
    "npm": "please-use-yarn",
    "node": "^10.16.0",
    "yarn": "^1.16.0"
  }

And
engine-strict = true in .npmrc

**Comment by kumavis** [comment]
relevant https://github.com/MetaMask/metamask-snaps-beta/issues/155
