### ISSUE TITLE
walletSendDomainMetadata causing unauthorized error in dapp console

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-plugin-beta#79]
- [ ] Logs an inaccurate unauthorized error in dapp console when
requesting permissions. Permissions request still succeeds.

**Comment by jennypollack** [comment]
`method: "wallet_sendDomainMetadata"`

```
"Error: Unauthorized to perform action. Try requesting permission first using the `requestPermissions` method. More info available at https://github.com/MetaMask/json-rpc-capabilities-middleware
    at getEthProviderError (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:234669:10)
    at Object.unauthorized (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:234615:14)
    at Object.unauthorized (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:228574:31)
    at CapabilitiesController.providerMiddlewareFunction (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:228197:34)
    at eachMiddleware (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:145455:7)
    at chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:236001:9
    at replenish (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:235877:17)
    at chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:235882:9
    at _asyncMap (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:235999:5)
    at chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:236085:16"
```

**Comment by rekmarks** [comment]
This was due to issues with `metamask-inpage-provider` that are now resolved. We are henceforth only using this branch: https://github.com/MetaMask/metamask-inpage-provider/tree/plugins
