### ISSUE TITLE
cb is not a function error on successful metamask_state updates from plugins

### ISSUE THREAD

**Issue by jennypollack** [MetaMask/metamask-plugin-beta#83]
the functionality is working, but the errors are annoying
```
utils.js:31 MetaMask - RPC Error: cb is not a function 
{code: -32603, message: "cb is not a function", data: {…}, stack: "TypeError: cb is not a function↵    at MetamaskCon…fipdcaolliommnkkcnnahmhod/background.js:235999:5)"}
code: -32603
data: {originalError: {…}}
message: "cb is not a function"
stack: "TypeError: cb is not a function↵    at MetamaskController.setUseBlockie (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:12606:7)↵    at eval (eval at <anonymous> (eval at createScopedEvaluatorFactory (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:354149:12)), <anonymous>:7:21)↵    at Object.method (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:3206:30)↵    at CapabilitiesController.executeMethod (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:228261:58)↵    at CapabilitiesController.providerMiddlewareFunction (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:228200:14)↵    at eachMiddleware (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:145455:7)↵    at chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:236001:9↵    at replenish (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:235877:17)↵    at chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:235882:9↵    at _asyncMap (chrome-extension://bndjlajfipdcaolliommnkkcnnahmhod/background.js:235999:5)"
__proto__: Object
```

**Comment by rekmarks** [comment]
Ah, seems like stuff is missing because the calls or occurring in a plugin context. Would you be willing to open a PR fixing that error (e.g. making `cb = () => {}` by default, just something simple)?

**Comment by rekmarks** [comment]
@jennypollack did we end up fixing this or is the problem still there?

**Comment by rekmarks** [comment]
No longer relevant.
